version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "testpguser"
      POSTGRES_PASSWORD: "testpgpassword"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"